name: "Install shunit2"
description: "Install shunit2 from https://github.com/kward/shunit2"

runs:
  using: "composite"
  steps:
    - name: Install shunit2
      run: |
        curl -sLo /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2
        chmod +x /usr/local/bin/shunit2
      shell: bash
