name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-shunit2
      - uses: sigoden/install-binary@v1
        with:
          repo: GoogleCloudPlatform/berglas
      - name: Run tests
        run: test/trivy-post.test.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
